import dynamic from 'next/dynamic'
import { useEffect, useState } from 'react'
import SpriteText from 'three-spritetext'
import { CSS2DRenderer } from 'three-stdlib'

import Checkbox from '@/components/checkbox'
import useDeviceDetect from '@/hooks/useDeviceDetect'

const ForceGraph3D = dynamic(() => import('react-force-graph-3d'), {
  ssr: false,
})

//MAIN
export const ForceGraph = ({ englishData, arabicData, isEnglish }) => {
  const { isMobile } = useDeviceDetect()

  const [hardcodedDefaultVisibleNodesIds, setHardcodedDefaultVisibleNodesIds] = useState([])
  const [hardcodedDefaultVisibleNodes, setHardcodedDefaultVisibleNodes] = useState([])
  const [clickedNodes, setClickedNodes] = useState([])
  const [duringSessionNodesIds, setDuringSessionNodesIds] = useState([])
  const [duringSessionNodes, setDuringSessionNodes] = useState([])
  const [visibleNodesIds, setVisibleNodesIds] = useState([])
  const [completeSetOfNodes, setCompleteSetOfNodes] = useState([])

  let graphData = isEnglish ? englishData : arabicData

  useEffect(() => {
    graphData = isEnglish ? englishData : arabicData

    setHardcodedDefaultVisibleNodesIds(
      isEnglish ? hardcodedEnglishDefaultVisibleNodesIds : hardcodedArabicDefaultVisibleNodesIds
    )

    setPhases(isEnglish ? englishPhases : arabicPhases)
    setSelectedTags([])

    setDuringSessionNodesIds(isEnglish ? englishDuringSessionNodesIds : arabicDuringSessionNodesIds)
  }, [isEnglish])

  useEffect(() => {
    setHardcodedDefaultVisibleNodes(graphData.nodes.filter((n) => hardcodedDefaultVisibleNodesIds.includes(n.id)))
    setVisibleNodesIds(hardcodedDefaultVisibleNodesIds)
  }, [hardcodedDefaultVisibleNodesIds])

  useEffect(() => {
    setCompleteSetOfNodes(hardcodedDefaultVisibleNodes)
  }, [hardcodedDefaultVisibleNodes])

  useEffect(() => {
    setDuringSessionNodes(graphData.nodes.filter((n) => duringSessionNodesIds.includes(n.id)))
  }, [duringSessionNodesIds])

  useEffect(() => {
    setVisibleNodesIds(isMobile ? duringSessionNodesIds : hardcodedDefaultVisibleNodesIds)
    setCompleteSetOfNodes(isMobile ? duringSessionNodes : hardcodedDefaultVisibleNodes)
  }, [isMobile])

  // CHILDREN
  const getNodeChildren = (nodeId) =>
    graphData.links.filter((l) => {
      return l.source.id === nodeId
    })

  const getNodeChildrenIds = (nodeId) => {
    let children = getNodeChildren(nodeId)
    return children.map((l) => l.target.id)
  }

  const getAllDescendantIds = (nodeId) => {
    const childrenIds = getNodeChildrenIds(nodeId)
    let descendants = []

    childrenIds.forEach((childId) => {
      descendants.push(childId)
      const childDescendants = getAllDescendantIds(childId)
      descendants = descendants.concat(childDescendants)
    })

    return descendants
  }

  // NODES
  // Set initially shown nodes
  const hardcodedEnglishDefaultVisibleNodesIds = [
    'Trace back  course of \n the session',
    'Who designed the game?',
    'Self-reflection on \n facilitator role',
    'Resort to external perspective',
    'How did the game \n boundaries perform?',
    'How was the group dynamic?',
    'Concepts we played with',
    'With obvious physical \n aspects to them',
    'With wide interpretations \n for physical application',
    'First grouping OP',
    'Second grouping OP',
    'First grouping WI',
    'Second grouping WI',
    'Insight from reflections \n and videos',
    'Phase',
    'During session',
    'During street intervention',
    'During workshops with groups',
    'Post-session reflection',
    'Reflecting on workshop',
    'Reflection on street intervention',
    'Pre-session planning',
    'Session is asked for by \n a client/partner/collaborator',
    'Planning a street intervention',
    'Upcoming session is part \n of a sequence of workshops \n or program',
    'Plan the session',
    'Insights from reflections \n and videos',
    'During session',
    'Pre-session planning',
    'Post-session reflection',
    'During street intervention',
    'During workshops with groups',
    'Work on setup',
    'Cultivate open mindset',
    'Tending the creative process',
    'Communicate prompt to passersby',
    'Set the ground',
    'Take care of logistics',
    'Communicate game boundaries',
    'Guide warm-up',
    'Cultivate facilitator mindset',
    'In facilitating the session',
    'Facilitate reflection',
    'Reflection on street intervention',
    'Reflecting on workshop',
    'Trace back  course of \n the session',
    'Synthesize',
    'Take note of all mini-games \n ideas which emerge from \n this process',
    'Look at piece with a distance \n from its creation process',
    'Was setup intuitive and attractive?',
    'About the facilitation',
    'Evolution of experience',
    'Consequences of our presence \n on the street',
    'Upcoming session is part \n of a sequence of workshops \n or program',
    'Upcoming session is \n a one time event',
    'Session is self-initiated',
    'Session is asked for by \n a client/partner/collaborator',
    'Main field of interest',
    "Do an in-depth inquiry to understand \n partner's needs",
    'Look to understand all \n characteristics of the project',
    'Service sought for',
    'Determine context of intervention',
    'Interventions in public space \n using simple prompts to \n allow passersby to indirectly \n create together',
    'Plan the setup',
    'What material are we using?',
    "What's the game like?",
    'Program flow and strategy',
    'Look at synthesis from previous session',
    'Actively wander, be receptive',
    'Plan the session',
    'Decide on introductory \n questions and explanations',
    'Organize flow of the session',
    'Define the game boundaries',
    'Choose material',
    'Plan warm-up adequate \n for the game',
    'First grouping insights',
    'Second grouping insights',
    'Third grouping insights',
  ]

  const hardcodedArabicDefaultVisibleNodesIds = [
    'المرحلة',
    'خلال الجلسة',
    'خلال تدخل الشارع',
    'خلال ورش العمل مع المجموعات',
    'إنعكاس ما بعد الجلسة',
    'التفكير في الورشة',
    'إنعكاس عن التدخل في الشارع',
    'تخطيط ما قبل الجلسة',
    'التخطيط للتدخل في الشارع',
    'التخطيط للجلسة',
    'تم طلب الجلسة من قبل \n زبون / شريك / متعاون',
    'المفاهيم التي لعبنا بها',
    'مفاهيم استنتجت من الانعكاسات \n ومقاطع الفيديو',
    'الجلسة القادمة جزء \n من سلسلة ورش عمل أو برنامج',
    'راجع مسار الجلسة',
    'من صمم اللعبة؟',
    'انعكاس ذاتي على \n دور الميسر',
    'اللجوء إلى نظرة خارجيّة',
    'كيف كانت أداء \n حدود اللعبة؟',
    'كيف كانت ديناميكية المجموعة؟',

    'مفاهيم استنتجت من الانعكاسات \n ومقاطع الفيديو',
    'مفاهيم استنتجت من الانعكاسات \n ومقاطع الفيديو',
    'مفاهيم استنتجت من الانعكاسات \n ومقاطع الفيديو',
  ]

  // RENDERING
  const [extraRenderers, setExtraRenderers] = useState([])
  useEffect(() => {
    setExtraRenderers([new CSS2DRenderer()])
  }, [])

  // ANCESTORS
  const nodeAncestors = (node) => {
    const parents = graphData.links.filter((l) => l.target.id === node.id)
    if (parents.length === 0) {
      return []
    }

    return parents.map((p) => p.source).concat(parents.flatMap((p) => nodeAncestors(p.source, graphData.links)))
  }

  Array.prototype.max = function () {
    return Math.max.apply(null, this)
  }



  // TAGS
  const englishPhases = ['Pre-session', 'During session', 'Post-session']
  const arabicPhases = ['ما قبل الجلسة', 'خلال الجلسة', 'ما بعد الجلسة']

  const [phases, setPhases] = useState([])

  const selectTag = (tag, selectedTags, setSelectedTags) => {
    if (selectedTags.includes(tag)) {
      setSelectedTags(selectedTags.filter((t) => t !== tag))
    } else {
      setSelectedTags([...selectedTags, tag])
    }
  }

  // CLICK
  useEffect(() => {
    if (clickedNodes.length > 0) {
      let firstClickedNodeId = clickedNodes[0]
      let firstClickedNode = graphData.nodes.find((n) => n.id === firstClickedNodeId)
      firstClickedNode.color = 'rgba(228, 255, 0, 1)'
    }
  }, [clickedNodes])

  const dimNodeAndChildren = (node, links) => {
    let grandchildrenIds = getAllDescendantIds(node.id)
    if (grandchildrenIds.length == 0) {
      grandchildrenIds = [node.id]
    }
    setVisibleNodesIds(visibleNodesIds.filter((id) => !grandchildrenIds.includes(id)))
    setClickedNodes(clickedNodes.filter((id) => !grandchildrenIds.includes(id) && id !== node.id))
  }

  const undimNodeAndChildren = (node, links) => {
    let childrenIds = getNodeChildrenIds(node.id, links)
    if (childrenIds.length == 0) {
      childrenIds = [node.id]
    }

    setVisibleNodesIds(visibleNodesIds.concat(childrenIds))
    setClickedNodes(clickedNodes.concat(node.id))
  }

  const handleNodeClick = (node) => {
    // Click on any other node
    if (!clickedNodes.includes(node.id)) {
      undimNodeAndChildren(node, graphData.links)
    }

    // Collapse node
    else {
      dimNodeAndChildren(node, graphData.links)
    }
  }

  // PANEL
  const [selectedTags, setSelectedTags] = useState([])
  const [isRevealed, setIsRevealed] = useState(false)

  const isVisible = (node) => {
    if (node.tags) {
      return node.tags.some((tag) => selectedTags.includes(tag))
    }
    return false
  }

  useEffect(() => {
    if (isRevealed) {
      setCompleteSetOfNodes(graphData.nodes)
    } else {
      setCompleteSetOfNodes(isMobile ? duringSessionNodes : hardcodedDefaultVisibleNodes)
    }
  }, [isRevealed])

  useEffect(() => {
    if (selectedTags.length !== 0) {
      let visibleNodes = completeSetOfNodes.filter((node) => isVisible(node))
      setVisibleNodesIds(visibleNodes.map((node) => node.id))
    } else {
      setVisibleNodesIds(completeSetOfNodes.map((node) => node.id))
    }
  }, [selectedTags, completeSetOfNodes])

  // VIEW
  return (
    <>
      {!isMobile && (
        <div className="z-50 mt-2 mb-2 mr-2 flex h-full w-full flex-row">
          {phases.map((phase) => {
            return (
              <div className="mr-3 flex flex-row" key={phase}>
                <Checkbox
                  label={phase}
                  checked={selectedTags.includes(phase)}
                  onCheckedChange={() => selectTag(phase, selectedTags, setSelectedTags)}
                />
              </div>
            )
          })}
          <Checkbox
            label={isEnglish ? 'Reveal' : 'كشف'}
            checked={isRevealed}
            onCheckedChange={() => {
              setIsRevealed(!isRevealed)
            }}
          />
        </div>
      )}
      {/* <Button
        onClick={(e) => {
          e.preventDefault()
          setIsRevealed(!isRevealed)
          if (isRevealed) {
            resetFilters()
          } else {
            expandAll()
          }
        }}
      >
        {isRevealed ? 'Reset' : 'Reveal'}
      </Button> */}

      {/* <Select
        phases={phases}
        // topics={getTags(graphData).filter((t) => !phases.includes(t))}
        selectedTags={selectedTags}
        onValueChange={(tag) => selectTag(tag, selectedTags, setSelectedTags)}
        open={isTagsPanelOpen}
        onOpenChange={setIsTagsPanelOpen}
        forceClose={forceClose}
        closeSelect={() => setForceClose(true)}
      /> */}
      <div className="fixed left-0 top-0 z-10 flex h-full w-full flex-col align-middle">
        <ForceGraph3D
          // RENDERING
          extraRenderers={extraRenderers}
          // DATA
          graphData={graphData}
          nodeId="id"
          linkSource="source"
          linkTarget="target"
          // CONTAINER
          backgroundColor="black"
          showNavInfo={false}
          // NODES
          nodeRelSize={10}
          nodeVal={(node) => {
            node.group
          }}
          nodeLabel={() => ''}
          nodeThreeObject={(node) => {
            const label = node.id
            const sprite = new SpriteText(label)
            sprite.textHeight = 6
            sprite.color = visibleNodesIds.includes(node.id) ? 'rgba(255, 255, 255, 0.9)' : 'rgba(255, 255, 255, 0)'
            sprite.fontSize = 25
            return sprite
          }}
          nodeThreeObjectExtend={true}
          nodeAutoColorBy={(node) => node.color}
          nodeVisibility={(node) => visibleNodesIds.includes(node.id)}
          nodeOpacity={0.5}
          nodeResolution={32}
          // ACTIONS
          onNodeClick={isMobile ? () => {} : handleNodeClick}
          // LINKS
          linkWidth={(link) => {
            if (clickedNodes.includes(link.source.id)) {
              return 2
            } else {
              return 1
            }
          }}
          linkColor={(link) => {
            if (clickedNodes.includes(link.source.id) && visibleNodesIds.includes(link.target.id)) {
              return 'rgba(228, 255, 0, 1)'
            } else {
              return 'rgba(255, 255, 255, 0.3)'
            }
          }}
          linkOpacity={0.5}
        />
      </div>
    </>
  )
}

const englishDuringSessionNodesIds = [
  'Phase',
  'During session',
  'During street intervention',
  'Setup intervention area',
  'Make it clear and practical',
  'Use specificities of location',
  'Communicate prompt to people',
  'Connect with the situation created',
  'Cultivate open mindset',
  'Prompt open to interpretation',
  'Explain purpose/meaning',
  ' Open space  for diversity',
  'Embrace interpretations of participants',
  'Tend to the creative process',
  'Be attentive to phases of \n evolution of the piece',
  'Take part of the action',
  'Help piece come together',
  "Do not overpower \n participants' action",
  'Which put work out of balance',
  'Highly significant actions',
  'Which bring it \n all together',
  'Which get reproduced \n by others',
  'Moments which mark a transformation',
  "Listen to changes in \n passersby's remarks",
  'Keep up with evolution \n of the piece',
  'During workshops with groups',
  'Set the ground',
  'Take care of logistics',
  'Communicate game boundaries',
  'Guide warm-up',
  'Cultivate facilitator mindset',
  'Facilitate the session',
  'Facilitate reflection',
  'Can put tools at their \n disposal',
  'Explain purpose of session',
  'Ask questions related \n to past session',
  'Commonly agree on \n ethics and habits',
  'Guide session flow',
  'Hold the space',
  'Speak from the heart',
  'Perceiving sessions as an evolutionary \n creative process',
  'Centered, playful and aware',
  'Flexible and embracing \n of uncertainty',
  'Egalitarian',
  'Prepare pre-requisite for the game',
  'Prepare mindset',
  'Warm-up the body',
  'Show example (if needed)',
  'Lusory attitude=playing out \n of their own free will',
  'Essentials of the game area',
  'Get session filmed for \n future reflection',
  'Various small tasks',
  'Prepare music playlist',
  'Game description',
  'Number of creations',
  'Singular',
  'Multiple',
  'All the focus is on \n one creation',
  'Interdependent creations evolving simultaneously',
  'Gameplay',
  'Environment/Setup',
  'Open dialogue',
  'Look at and analyze result',
  'How is it read?',
  'Is color or form \n taking priority?',
  'As a mood/energy',
  'Provide platform for \n their notes',
  'Give perspective to experience \n from place of learning',
  'Participants, playing as',
  'I ran from all my heart \n forgot about everything \n I was completely absorbed',
  'Role playing',
  'Playing as self',
  'Identifying self as character \n within the bounds of play',
  'Games  absorb  players \n into second reality',
  'Type of game',
  'Theme',
  'Determine game language',
  'How is it played?',
  'Rules of the game',
  'How rigid are the rules?',
  'Playing with and \n testing boundaries',
  'Paradoxically needs limits',
  'Need to be clearly understandable',
  'Drawings can help',
  'Rigid/tight',
  'Open/loose',
  'Who decided them?',
  'Agreed upon by all \n participants',
  'Enforced by one person',
  'Impossible without trust',
  'Creates a very enjoyable \n effective, experience',
  'Can feel oppressive if faced \n with undealt with resistance',
  'Is an exercise in collective \n decision making',
  'Goal needs to be very clear',
  'Potentials of strictness',
  'Gets things organized',
  'Time efficient',
  'Makes comparing experiences \n possible',
  'Setbacks of strictness',
  'Can limit exploration \n and innovation',
  'Can constrain sense of \n initiative',
  'More chaos allowed',
  'Has requirements to \n be constructive',
  'Shared sense of safety',
  'From the facilitator',
  'Presence and high flexibility',
  'Shared broad direction',
  'Distinguish between constructive and \n destructive behavior',
  'From the players',
  'The logic of the game \n as a clear limit',
  'Strong interaction \n between them',
  'Leads to emergence of \n clusters of action',
  'First signs of formation \n of a microsociety',
  'Consciously aware of each other',
  'Creative potentials of chaos',
  'Energetic and exhilarating',
  'Accidental chance occurences',
  'Grasping the opportunity \n leads to transformation',
  'Emergence of new order',
  'In par with natural evoution',
  'Essential for self-guided \n learning',
  'Openness triggers self-initative',
  'Results in complex behavior',
  'Triggers out of the box thinking',
  'Destructive risks of chaos',
  'High intensity',
  'All boundaries and direction \n  can become unclear',
  'Can be tough to take back the \n guidance of the session',
  'Tends to become draining',
  'Creative process can get \n entangled with group dynamics',
  'Actions',
  "What's the goal?",
  'Time signature',
  'Materials used',
  'Game setting',
  "Who's responsible for \n the game design?",
  'Facilitator',
  'Participants during session',
  'Adjust plan according \n to emerging situation',
  'Alternate exercises, games \n and reflections',
  'Allocate adequate materials \n to each phase',
  'Keep up momentum of session',
  'We all gather for the reflection',
  "Add on, don't cancel",
  'There are appropriate times for \n propositions and others for action',
  'Keep chaos constructive',
  'Facilitate meaningful dialogue',
  'Strengthen human connection',
  'Stay attuned to the \n  creative process',
  'Create space for their initiatives',
  'Participate when needed',
  'Never enforce ideas',
  'Technique of tools',
  'Personal, individual creation',
  'Is location indoors \n or outdoors?',
  'Is it a familiar or \n new space?',
  'How can materials \n be layed out?',
  'Who sets up the \n  game space?',
  'How are we using \n  the environment?',
  'Our game is highly contextual',
  'Same game could be \n played anywhere',
  'Facilitator before players arrive',
  'Players as an integral part \n of the experience',
  'Physical stance of the players',
  'Sitting',
  'Standing',
  'At ground level',
  'In movement',
  'Types of layouts',
  'Centralized focus',
  'Immersive and spatial',
  'Separate clusters \n of action',
  'Spread out surfaces \n for action',
  'In linear formations',
  'In radial formations',
  'Effects of centralizing',
  'Focused attention',
  'Energy transmits easily',
  'Effects of decentralizing',
  'Triggers exploration',
  'Activates physical movement \n in space',
  'Engaging social experience',
  'Discover natural affinities',
  "Dynamic highly sensitive to \n each participant's input",
  'Shy participants might retreat',
  'Proactive participants might \n take all',
  'Attention can drift off topic',
  'Could be challenging to \n re-gather the energy',
  "What's the scale?",
  'Players take action ON \n the game',
  'Players take action WITHIN \n the game',
  "How's the layout?",
  'Accessibility of tools',
  'Location of action',
  'Lighting',
  'Is light an integral \n part of the experience?',
  'What does it consist of?',
  'Open game',
  'Closed game',
  'Engages competition',
  'Instinctively create a lot of \n excitement',
  'Engages cooperation',
  'Combination',
  'Alternates both types',
  'Reaching goal is the \n end of the game',
  'Reaching goal keeps \n the game going',
  'Competition needs collaboration \n in adhering to the rules',
  'Affects the mood of \n the session',
  'Are we using chance?',
  'Individually',
  'Self explorations joining in \n a collective creation',
  'Collective exploration creates \n collective creation',
  'Collectively',
  'In small groups',
  'Task could need organization',
  'Facilitator can provide \n initial guidance',
  'Facilitator can  observe their \n approach w/out guidance',
  'Open it up for reflection',
  'Collective decision making',
  'Close cooperation',
  'Situation with high \n learning potential',
  'Is very sensitive \n to group dynamics',
  'Is smoother when \n individuals are',
  'Easy-going, open, mindful \n of others',
  'Able to have dialogue',
  'Each playing their part',
  'Creates equal ground',
  'Creates a link with deep \n outlooks on life',
  'Relieves people from \n need of control',
  'Two-Dimensional',
  'What constrains the creation?',
  'Rules give form to the \n infinity of possibilities',
  'Skills of any level can \n participate',
  'Its evolution in time',
  'One continuous evolution \n tending towards entropy',
  'Time divided to different phases',
  "Players' interaction",
  'Through layering of actions',
  'Is indirect communication',
  'Action and reception are \n separate in time',
  'Aspect of resulting image',
  'Texture of time',
  'Traces of actions',
  'Dynamic entanglement of \n evocative forms',
  'Three-Dimensional',
  "What's it made of?",
  'Affected by material constraints',
  'Gravity/balance',
  'Bendability/solidity',
  "What's needed to join \n two pieces together?",
  'Material characteristics',
  'Dimensions/weight',
  'Builders interact through',
  'Strong potential of reaching \n collective flow',
  'Assemblage',
  'Material manipulation',
  'Direct collaboration',
  'Resulting object or installation',
  'Is comprehended as',
  'Whole figure',
  'Immersive space',
  'Can easily become element \n of another game',
  'Physical movement',
  'Bodies as elements of \n the game',
  'Rules as behavioral constraints',
  'Which reinforce feedback loop',
  'High physical interaction',
  'Close contact and sensorial \n activation',
  'Create systematic motion',
  'Visual result',
  'Choreographic visual result',
  'Extraordinary collective \n behavior',
  'Combination of languages',
  'Living systems',
  'Can be inspired from',
  'Personal experience',
  'Open questions',
  'Dialectical subjects',
  'Human psychology',
  'Found material',
  'Questions arising from \n real life situations',
  'Established practices',
  'Art or craft making processes',
  'Board games/video games \n sports',
  'Circus and performative arts',
  'Environmental, social \n economic or political ',
  'Creates a story',
  'Makes the game more relatable',
  'Finding its essential parts \n is very helpful for the game',
  'Types of rules',
  'Are required for',
  'Their clarity and success \n affects future steps',
  'Fixed rules',
  'Variable rules',
  'Creating a positive tension \n and a feedback loop',
  "Blending players' actions",
  'Limiting the actions possible',
  'Setting limits to \n verbal communication',
  'Are personal expressions',
  'Are physical traces',
  'Trigger more then one \n physical movement',
  'Emerge from the self',
  'Give creative outlet \n for impulses',
  'Create a common language',
  'Simple, incrementally \n reach complexity',
  'Are a personal mark',
  'Can be sourced from',
  'We can make something from anything',
  'What can be done with \n what we have?',
  'Transform the space',
  'Have history',
  'Material available on location',
  'Ready-mades',
  'Objects, magazines, images',
  'Their transformation creates \n unexpected meanings',
  'Quantity of raw material',
  'Advantages of re-using',
  'Giving value back w/out \n manufacturing anew',
  'Types of material found',
  'Simple manipulations feel \n like breakthroughs',
  'Less pressure and expectations',
  'Natural material',
  'Rich with details',
  'Can have very \n evocative forms',
  'Have a strong aesthetic',
  'Leaves no trash',
  ' Reconnect with \n natural world',
  'Store bought',
  'Stationary',
  'Some participants can feel \n pressured by expectations',
  'Opportunity to change \n preconceived ideas',
  'Opportunity to learn in \n open environment',
  'Opportunity to try',
  'Hardware',
  'Inspires curiosity \n no pressure',
  'Some core tools are \n re-used in many sessions',
  'Trace making',
  'Fluid materials',
  'Dry materials',
  'What is seen is the direct \n impact of the action',
  'Colors',
  'An entry into different \n types of crafts',
  'Can be used to harmonize',
  'Action they will be \n used for',
  'Moldable types',
  'Can be used to play with shadow',
  'Non precious',
  'Morphs beyond the direct \n impact of the action',
  'Can really stimulate imagination',
  'Building',
  'Material types',
  'Solid materials',
  'Flexible types',
  'Required characteristics',
  'Easy to use and process',
  'Offer potentials of play',
  'Players build connection \n through  materials',
  'Sharing tasks',
  'Worksite atmosphere \n creates flow',
  'Affect the energy released ',
  'High and loud',
  'Smooth and calm',
  'Require tools for processing',
  'A direction which results \n in a collective creation',
  'Gives incentive to keep \n the game going',
  'A build up on the theme',
  'Duration and division of time',
  'Note: All sessions happen within \n  divided entropy ',
  'Entropy',
  'Short defined time',
  'Types of time divisions',
  'Alternates playing/reflection',
  'Allows for comparative \n iteration',
  'Requires stricter rule keeping \n for efficiency',
  'Limit the amount of rules \n added each time',
  'Can keep up momentum',
  'Opens space for discussion',
  'Risks too much verbal \n communication',
  'Inclusive',
  'Loses momentum',
  'Is a natural progression',
  'We can observe different \n phases of evolution',
  'Players can enter state \n of flow',
  'Can have rising or losing \n momentum',
  'Radical transformation can happen \n during gameplay',
  'Ongoing expansion in expanding time',
  "Timing of players' actions",
  'Simultaneous direct interaction',
  'Successive indirect interaction',
  'Allows for all participants to \n observe progression',
  'Slower rhythm then simultaneity',
  'If too slow it kills momentum',
  'Opens space for strategic \n and rational thinking',
  'Creates an energizing atmosphere',
  'Worksite atmosphere',
  'Triggers collective drive',
  'Spontaneous interactions',
  'Going with the flow',
  'Exchange of skills by \n observation',
  'Makes it easier to reiterate',
  'Stimulates the senses',
  'Can be overwhelming',
  'Shakes participants out of \n comfort zone',
  'For some its transformational',
  'For some its frustrating',
  'From the game',
  'From the group dynamics',
  'Linking observations to theories',
  'Opening a safe space \n for diverging opinions',
  'Finding different ways of getting \n ideas understood',
  'Self-perceived limits \n are respected',
  "It's a non judgemental space \n to learn about each other",
  'Of the players',
  'Of the piece/experience',
  'Collectively attuned',
  'Listening & looking at \n each other',
  'Making collective decisions',
  'Individually attuned',
  'Confident',
  'Willful',
  'Playful',
  'Spontaneous and intuitive',
  'Into the theme and world \n of the game',
  'Gather energy',
  'Collect our minds',
  'Starting together sets \n the pace for the session',
  'Sensorially attuned',
  'Heightened energy to  enter \n the creative flow',
  'Connected to the breath',
  'How does it trigger imagination?',
  'How can we develop \n this process?',
  'How does it contribute to \n our understanding?',
  'About the boundaries \n of the experience',
  'About warm-up',
  'About individual experiences',
  'About special situations',
  'Potentially a main inspiration \n for next session',
  'About collective work',
  'Changes which happened to \n their perceptions',
  'Extract  ideas \n for next session',
  "From participants' requests",
  'About the theme, techniques \n and materials',
  'About reinterpreting \n a known game',
  'Facilitator can reinterpret \n the requests',
  'From small details \n during discussions',
  'From synthesis of reflection',
  'Proposes a game developed \n pre-session',
  'Players experience and reflect \n on the game',
  'All rules are open for change',
  'Have the initiative and \n decide boundaries',
  ' Make collective decisions',
  'Creating the game is \n the creative process',
  'Facilitation required',
  'Time keeping',
  'Keeping it inclusive',
  'Encouraging iteration and trial',
  'Set target on gameplay not roleplay',
  'Define the logic of the game',
  'Affect the gameplay but \n not the logic',
  'The game element exists \n within there',
  'If they are effective in \n stimulating the players',
  'Trials experiment with \n the variable rules',
  'To explore different flows \n of interaction',
  'To reach more complexity \n in the result/experience',
  'Theme is there but \n gameplay is not engaging',
  'Trials aim to find the game \n within these boundaries',
  'If its unbounded',
  'If its clearly dedicated to \n reflection & planning phases',
  'Gives possibility to find \n shared vision',
  'Risks an atmosphere of \n judgement and criticism',
  'Shy players might not speak up',
  'Creative process might \n become too rational',
  'Favors intuitive communication \n during gameplay',
  'Facilitates acceptance and flow',
  'Rules can counter potential \n setbacks of verbal communication',
  'The challenges of communication \n offer much to play with',
  'Without aesthetic judgement',
  'Propose ideas when possible',
  'Help with use of tools',
  'Put complementaries together',
  'Help bypass their blockages',
  'Push to explore their potential',
  'The interactions created by \n the game',
  'The dynamics emerging',
  'Are actions merging \n creating complexity?',
  'The actions of each participant',
  "If they're doing something else \n what is it?",
  'Identify key moments',
  'When did meaning emerge?',
  'When did group \n get into a flow?',
  'What events affected \n the whole progression?',
  'An idea transmitting \n to all players',
  'Interactions changing the dynamic',
  'Curious and experimental',
  'Most creative state \n of being',
  'Inclusive of differences',
  'Get acquainted with \n the symbolism',
  'Getting a hint of \n the challenge',
  'Non-hesitant automatism',
  'Making free-associations',
  'Bypassing the rational',
  'Sharing allows us to feel \n our perception matters',
  'Sharing allows us to recognize \n similarities with others',
  'Positives and negatives',
  'How did they work together \n through their challenges?',
  'How does each feel about \n collective work',
  'If a tense situation occurs',
  'Allow it to happen talk \n about it in reflection',
  'Deal with it directly',
  'How to allow a smooth \n communication?',
  'Keeping in mind their own \n ability to self-regulate',
  'Did players feel well \n prepared?',
  'Was its length adequate?',
  'As as general outline',
  "What did or didn't work \n as expected?",
  'What makes it good?',
  'What makes it fail?',
  'About rules',
  'Were they clear and challenging?',
  'Did they create interaction \n and momentum?',
  'How else could we have \n tried to play it?',
  'About the actions',
  'What mood are they \n adequate for?',
  'Were they intriguing and meaningful?',
  'Did they provide enough \n choice and diversity?',
  'How did participants relate \n to the material?',
  'Did its manipulation feel \n instinctive?',
  'Did we have adequate tools?',
  'Did it trigger something particular?',
  'Was the purpose clear?',
  'Was the formulation adequate?',
  'Did it create the drive?',
  'Does it help their visions to \n find common ground?',
  'Concepts we played with',
  'Tangible inspirations',
  'Intangible inspirations',
  'With obvious physical \n aspects to them',
  'First group OP',
  'Second grouping OP',
  'With wide interpretations \n for physical application',
  'First grouping WI',
  'Second grouping WI',
  'Third grouping WI',
  'Simulating our living systems',
  'Reproduction of a personal graphic element',
  'Use of shadow to morph shapes',
  'Re-adaptation of board and video games ',
  'Bounding the trace to contours of objects ',
  'Creation of imagery from \n collective story telling',
  "Balance as a link \n between players' action",
  'Analyzing known games to get inspired',
  'Connecting through the material \n building, construction',
  "'House' with Zayraqoun'",
  'Building our own musical instruments',
  'Starting the game with the setup',
  'Games from real life \n challenges',
  'Rules which create choreographies',
  'Free will and determinism',
  'Dancing to an emerging image',
  "Who's oppressing who?",
  'Creating laboratory contexts',
  'Entangled collective unconscious',
  'Bonding through dreams',
  'The game area as coexistence ',
  'Collective understanding through \n critical reflection',
  'What insights have we \n reached through editing the video?',
  'Insights from reflections \n and videos',
  'Insights from reflections \n and videos',
  'First grouping insights',
  'Second grouping insights',
  'Third grouping insights',
  'Building as the first \n collective creative acts in history',
  'Patterns emerge from chaos \n in small sequences',
  'Without awareness the meaning \n gets lost',
  'Self-knowledge is the first bridge \n towards others',
  'Playgrounds as spaces we need \n to learn to be ourselves with others',
  'Every situation has a game to it',
  'Better rules can make \n better play',
  "The experience isn't defined by the goal",
  'Balance as a path of exploration',
  'Culture as simultaneity of \n creative experiences',
  'Cheating is play, up until \n cheating ruins the game',
  'Collective knowledge as the coming \n together individual knowledges',
  'One individual cannot \n understand everyone',
  'Reflection is the heart of the experience',
  'Building games \n builds meaningful relationships',
  'Syncing through physical entanglement',
  'Observations about cheating',
  'Reveals areas where rules \n can be added',
  'Cannot challenge logic \n of the game',
]

const arabicDuringSessionNodesIds = [
  'المرحلة',
  'خلال الجلسة',
  'خلال تدخل الشارع',
  'إعداد منطقة التدخل',
  'اجعلها واضحة وعملية',
  'استخدام خصوصيات الموقع',
  'مكالمة القانون الموجّه للناس',
  'التواصل مع الوضع الذي تم إنشاؤه',
  'تنمية العقلية المنفتحة',
  'القانون قابل لتعدديّة التفسيرات',
  'شرح الهدف/ المعنى',
  'فضاء مفتوح للتنوع',
  'تقبل تفسيرات المشاركين',
  'الأهتمام بالعملية الإبداعية',
  'انتبه لمراحل   \n تطور القطعة  ',
  'شارك في العمل',
  'تفعيل تركيب الصورة',
  ' لا تطغى على  \n أعمال المشاركين ',
  'ما يخّل في توازن العمل  ',
  'أفعال بالغة الأهمية',
  'التي تجمعها ',
  'التي تعاد \n بواسطة الآخرين',
  'اللحظات التي تشير إلى تحوّل',
  'استمع إلى التغييرات في \n ملاحظات المارة',
  'مواكبة تطوّر \n القطعة',
  'خلال ورش العمل مع المجموعات',
  'تمهيد المساحة',
  'اعتني باللوجستيات',
  'توصيل حدود اللعبة',
  ' تيسير التحماية',
  'تنمية عقلية الميسّر',
  'تيسير الجلسة',
  'تيسير الانعكاس',
  'شرح الهدف من الجلسة',
  'طرح أسئلة تتعلق \n بالجلسة السابقة',
  'إتفاق على الأخلاق والعادات الأساسيّة',
  ' توجيه مسار و توقيت الجلسة',
  ' رعاية الفضاء',
  'تكلم من القلب',
  'تصور الجلسات كعملية  \n إبداعية تطورية',
  'مركزة ،مرحة و واعية',
  'مرنة وتحتضن \n عدم اليقين',
  'مراعٍ للمساواة',
  'جهّز المتطلبات الأساسية للعبة',
  'تحضير العقلية',
  'إحماء الجسم',
  'إظهار المثال (إذا لزم الأمر)',
  'اللعب بإرادتهم الحرة',
  'أساسيات مساحة اللعبة',
  'صوّر الجلسة \n للانعكاس المستقبلي',
  'مهام صغيرة متنوعة',
  'تحضير قائمة تشغيل الموسيقى',
  'وصف اللعبة',
  'عدد الابتكارات',
  'ابتكار فرديّ',
  'ابتكارات متعدّدة',
  'كل التركيز على \n إبتكار واحد',
  'إبداعات مترابطة تتطور في وقت واحد',
  ' طريقة اللعب',
  'البيئة / الإعداد',
  'حوار مفتوح',
  'نظر إلى النتيجة وتحليلها',
  'كيف تقرأ؟',
  'هل اللون أو الشكل \n له الأولوية؟',
  'كمزاج / طاقة',
  'توفير مساحة تدوين \n لملاحظاتهم',
  'إعطاء منظور للتجربة \n من مكان تعلّم',
  'المشاركون ، يلعبون كـ',
  'ركضت من كل قلبي \n نسيت كل شيء \n اندمجت تمامًا',
  'لعب الأدوار',
  'اللعب كالذات',
  'تحديد الذات كشخصية \n ضمن حدود اللعب',
  'الألعاب تسحب اللاعبين \n في واقع ثاني',
  'نوع اللعبة',
  'ألموضوع',
  'تحديد لغة اللعبة',
  'كيف يتم لعبها؟',
  'قوانين اللعبة',
  'ما مدى صرامة القوانين ؟',
  'اللعب مع \n واختبار الحدود',
  'بحاجة إلى حدود',
  'يجب أن تكون مفهومة بوضوح',
  'الرسومات يمكن أن تساعد',
  'صارم / ضيق',
  'مفتوح / فضفاض',
  'من قررها؟',
  'موافق عليها من قبل كافة \n المشاركين',
  'مفروضة من قبل شخص واحد',
  'مستحيل بدون ثقة',
  'يخلق تجربة فعالة و ممتعة للغاية ',
  'يمكن أن تشعر بالقمع إذا واجهت \n مقاومة دون استيعابها',
  'تمرين في \n اتخاذ قرار جماعي',
  'يجب أن يكون الهدف واضحًا جدًا',
  'إمكانات الصرامة',
  'تنظيم الأشياء',
  'فعال من ناحية الوقت',
  'يجعل مقارنة التجارب ممكنة ',
  'نقاط ضعف الصرامة',
  'يمكن أن يحد من الاستكشاف \n والابتكار',
  'يمكن أن يقيد الشعور بالمبادرة ',
  'المزيد من الفوضى مسموح بها',
  'لديه متطلبات  \n ليكون بناء',
  'الشعور المشترك بالأمان',
  'من الميسر',
  'الحضور والمرونة العالية',
  'اتجاه واسع و مشترك',
  'التمييز بين السلوك البناء \n والسلوك التدميري',
  'مع اللاعبين',
  'منطق اللعبة \n كحدود واضحة',
  'تفاعل قوي بينهم',
  'يؤدي إلى ظهور \n تعدديّة من الإجراءات',
  'أولى علامات تكوين \n مجتمع صغير',
  'مدركين لبعضنا البعض',
  'الإمكانات الخلاقة للفوضى',
  'حيوية ومبهجة',
  'الفرص العرضية',
  'اغتنام الفرصة \n يؤدي إلى التحول',
  'ظهور نظام جديد',
  'على قدم المساواة مع التطور الطبيعي',
  'ضروري للتعلم الذاتي',
  'الانفتاح يسمح بالمبادرة الذاتية',
  'ينتج عنه سلوك معقد',
  'تحفّز التفكير خارج الصندوق',
  'مخاطر الفوضى المدمرة',
  'كثافة عالية',
  'يمكن أن تصبح كافة الحدود والاتجاه \n غير واضحة',
  'قد يكون من الصعب استعادة \n توجيه الجلسة',
  ' يميل إلى استنزاف الطاقة',
  'يمكن أن تتشابك العملية الإبداعية \n مع ديناميكيات المجموعة',
  'الأفعال',
  'ما هو الهدف؟',
  'التوقيت',
  'المواد المستخدمة',
  'إطار اللعبة',
  'من المسؤول عن \n تصميم اللعبة؟',
  'الميسّر',
  'المشاركون أثناء الجلسة',
  'اقلم الخطة وفقًا \n للحالة الناشئة',
  ' بدّل ما بين تمارين  \n    وألعاب وانعكاسات ',
  'تخصيص المواد المناسبة \n لكل مرحلة',
  'حافظ على زخم الجلسة',
  ' كلنا نجتمع للتفكير و الانعكاس',
  'أضف ، لا تلغي',
  'المحافظة على فوضى بناءة',
  'تيسير حوارات هادفة',
  'تعزيز التواصل البشري',
  'ابقى على اطلاع على \n العملية الإبداعية',
  'خلق مساحة لمبادراتهم',
  'المشاركة عند الحاجة',
  'عدم فرض الأفكار مطلقًا',
  'تقنية استعمال الأدوات',
  'ابتكار حميم فردي',
  'هل الموقع داخلي \n أم خارجي؟',
  'هل هي مساحة مألوفة أو \n جديدة؟',
  'كيف توضع المواد ؟',
  'من يقوم بإعداد \n مساحة اللعب؟',
  'كيف نستخدم \n البيئة؟',
  'لعبتنا سياقية للغاية',
  'يمكن لعب نفس اللعبة \n في أي مكان',
  'الميسر قبل وصول اللاعبين',
  'اللاعبون كجزء لا يتجزأ \n من التجربة',
  'موقف اللاعبين الجسدي ',
  'جلوس',
  'قائمين',
  'على مستوى الأرض',
  ' متحرّكين',
  'أنواع الترتيبات',
  'تركيز مركّز',
  'غامرة ومنتشرة',
  'مجموعات منفصلة \n من الأعمال',
  'أسطح عمل منتشرة',
  'في تكوينات خطية',
  'في تكوينات شعاعية',
  'آثار المركزية',
  'تركيز الاهتمام',
  'الطاقة تنتقل بسهولة',
  'آثار اللامركزية',
  'تفعّل الاستكشاف',
  'ينشط الحركة الجسدية \n في الفضاء',
  '  تجربة الاجتماعية مشتركة',
  'اكتشاف الصلات الطبيعية',
  'الديناميكيّة شديدة الحساسية \n لأفعال كل مشارك',
  'المشاركون الخجولون قد يتراجعون',
  'قد يأخذ المشاركون الاستباقيون \n كل شيء',
  'قد يكون من الصعب \n إعادة تجميع الطاقة',
  'ما هو المقياس؟',
  'يتخذ اللاعبون إجراءات على اللعبة',
  'يتخذ اللاعبون إجراءات داخل \n اللعبة',
  'كيف هو الترتيب العام؟',
  'سهولة الوصول إلى الأدوات',
  'موقع العمل',
  'إضاءة',
  'هل الضوء جزء لا يتجزأ من  \n التجربة؟',
  'مما تتكون؟',
  'لعبة مفتوحة',
  'لعبة مغلقة',
  'تفعّل المنافسة',
  ' غريزيًا تخلق الكثير من الإثارة ',
  'يفعّل  التعاون',
  'مزيج',
  'تعاقب بين كلا النوعين',
  'بلوغ الهدف هو \n نهاية اللعبة',
  'الوصول إلى الهدف هو \n   استمرار اللعبة',
  'المنافسة بحاجة إلى تعاون \n في التزام القوانين',
  'يؤثر على مزاج  الجلسة',
  'هل نستخدم الحظ؟',
  'بشكل فردي',
  'الاستكشافات الذاتية تنضم في \n إنشاء جماعي',
  ' الاستكشاف الجماعي ينشئ \n إنشاءًا جماعيًا',
  'جماعياً',
  'في مجموعات صغيرة',
  'قد تحتاج المهمة إلى تنظيم',
  'قد يعطي الميسّر \n توجيهات أوليّة',
  'قد يراقب الميسّر  \n سلوكهم بدون توجيهات',
  'فتحه للتفكير',
  'اتخاذ قرار جماعي',
  'تعاون وثيق',
  'موقف مع إمكانات تعليمية عالية ',
  'حساس للغاية \n لديناميات المجموعة',
  'يكون أكثر سلاسة عندما ',
  'مسهّل ، منفتح ، دارك  للآخرين',
  'قادر على الحوار',
  'كل واحد يلعب دوره',
  'يخلق أرضية متساوية',
  'يربط اللعب بنظرات  \n عميقة للحياة',
  'يريح الناس من  \n الحاجة إلى التحكم',
  'ثنائي الأبعاد',
  'ما الذي يقيّد الخلق؟',
  'القوانين تحصر \n الاحتمالات اللانهائية',
  'يمكن المشاركة في أي   \n  مستوى من المهارات',
  'تطورها في الوقت ',
  'تطور  مستمر \n يتجه نحو الانتروبيا',
  'الوقت مقسّم إلى مراحل مختلفة',
  'تفاعل اللاعبين',
  'من خلال تطابق الأفعال',
  'اتصال غير مباشر',
  'الإجراء والاستقبال \n منفصلان في الوقت ',
  'مظهر الصورة الناتجة',
  'نسيج الزمن',
  'آثار الأفعال',
  'التشابك الديناميكي \n للأشكال المفعمة بالحيوية',
  'ثلاثي الأبعاد',
  'مما هو مصنوع؟',
  'متأثر بقيود مادية',
  'الجاذبية / التوازن',
  'الانحناء / الصلابة',
  'ما المطلوب لضم \n قطعتين معًا؟',
  'الخصائص المادية',
  'الحجم / الوزن',
  'بناة يتفاعلون من خلال',
  'إمكانية قوية للوصول إلى \n التدفق الجماعي',
  'تجميع',
  'التلاعب بالمواد',
  'التعاون المباشر',
  'التركيب الناتج أو التجهيز',
  'يُفهم على أنه',
  ' الصورة الكاملة',
  'مساحة غامرة',
  'يمكن أن تصبح عنصرًا \n في لعبة أخرى',
  'الحركة الجسدية',
  'الأجسام كعناصر اللعبة',
  'القوانين كقيود سلوكية',
  'مما يعزز نشوء حلقة',
  'تفاعل جسدي مرتفع',
  'تواصل قريب وتنشيط للحواس ',
  'إنشاء حركة منتظمة',
  'النتيجة المرئية  تشابه الرقص',
  'مزيج من اللغات',
  'أنظمة حيويّة',
  'يمكن أن يكون مستوحى من',
  'خبرة شخصية',
  'أسئلة مفتوحة',
  'مواضيع جدلية',
  'علم النفس البشري',
  ' مادة تم العثور عليها',
  'الأسئلة الناشئة عن \n مواقف حياتيّة',
  'الممارسات الراسخة',
  'عمليات صنع الفن أو الحرف اليدوية',
  'ألعاب لوحية / ألعاب فيديو / رياضة',
  'السيرك والفنون المسرحية',
  'بيئي أو اجتماعي \n اقتصادي أو سياسي',
  'يخلق قصة',
  'يخلق ترابط مع اللعبة ',
  'تحديد و تبسيط مفاهيمه الأساسية \n أساسي لتصميم اللعبة',
  'أنواع القوانين',
  'مطلوبة من أجل',
  'يؤثر وضوحها ونجاحها \n على الخطوات المستقبلية',
  'القوانين الثابتة',
  'القوانين المتغيرة',
  'خلق توتر إيجابي \n وحلقة تبادل',
  'مزج أفعال اللاعبين',
  'الحد من الأفعال الممكنة',
  'الحد من التواصل اللفظي',
  'هي تعبيرات شخصية',
  'هي آثار مادية',
  'تحريك أكثر من  \n حركة جسدية واحدة',
  'تنبع من الذات',
  'تعطي منفذاً إبداعيًا للاندفاع',
  'تنشاء لغة مشتركة',
  'بسيط ، بشكل متزايد \n يصل إلى التعقيد',
  'هي علامة شخصية',
  'يمكن الحصول عليها من',
  'فينا نعمل شيئًا من أي شيء',
  'ما الذي يمكن فعله بالموجود؟',
  'تحويل الفضاء',
  'لها تاريخ',
  'المواد المتوفرة في الموقع',
  ' جاهزة للاستعمال',
  'أشياء ، مجلات ، صور',
  'يؤدي تحولهم إلى \n معاني غير متوقعة',
  'كمية المواد الخام',
  'حسنات إعادة الاستخدام',
  'إعادة القيمة بدون \n التصنيع من جديد',
  'أنواع المواد التي عثر عليها',
  'تلاعبات بسيطة تتّاخذ \n كإختراقات',
  'ضغط وتوقعات أقل',
  'مواد طبيعية',
  'غنية بالتفاصيل',
  'يمكن أن يكون لها \n أشكال مثيرة للخيال',
  'لديها جمالية قوية',
  'لا تترك قمامة',
  'إعادة الاتصال  \n بالعالم الطبيعي',
  'اشترى في المتجر',
  'مكتبة',
  'قد يشعر بعض المشاركين \n بضغط التوقعات',
  'فرصة للتعلم \n في بيئة تجريبية',
  'خرضوات و معدّات',
  'يثير الفضول \n بدون ضغط',
  'يتم إعادة استخدام بعض الأدوات الأساسية \n في العديد من الجلسات',
  'وضع العلامات',
  'المواد السائلة',
  'مواد جافة',
  'ما يتم رؤيته هو التأثير المباشر \n للفعل',
  'الألوان',
  'إدخال إلى أنواع مختلفة \n من الحرف اليدوية',
  'يمكن استخدامها للانسجام',
  'الأفعال التي سيتم استخدامها \n من أجلها',
  'أنواع قابلة للتشكيل',
  'يمكن استخدامها لألعاب الظل',
  'غير ثمين',
  'تحويلات تتجاوز التأثير المباشر للإجراء ',
  'يمكن أن تحفز الخيال',
  'البناء',
  'أنواع المواد',
  'المواد الصلبة',
  'الأنواع المرنة',
  'الخصائص المطلوبة',
  'سهل الاستخدام والمعالجة',
  'تؤمّن إمكانات اللعب',
  'يقوم اللاعبون بالتواصل \n من خلال المواد',
  'تقاسم المهام',
  'جو ورشة العمل \n يخلق تدفقًا وانسجام',
  'تؤثر على الطاقة المنبعثة',
  'عالية وبصوت عال',
  'سلسة وهادئة',
  'تطلب أدوات للمعالجة',
  'اتجاه يؤدي \n إلى إنشاء جماعي',
  'يعطي حافزًا لمواصلة اللعبة',
  'يبني على الموضوع',
  'المدة وتقسيم الوقت',
  'ملاحظة: تحدث جميع الجلسات ضمن \n إنتروبيا مقسّمة',
  'إنتروبيا',
  'وقت محدد قصير',
  'أنواع التقسيمات الزمنية',
  'تعاقب بين اللعب و الانعكاس',
  'يسمح بالتكرار و المقارنة ',
  'يتطلب  قاعدة أكثر صرامة \n من أجل الفعاليّة',
  'الحد من كمّية القوانين \n المضافة في كل مرة',
  'يمكن أن تحافظ على الزخم',
  'يفتح مساحة للمناقشة',
  'خطر في كثرة الكلام',
  'جامع',
  'يفقد الزخم',
  'هو تطور طبيعي',
  'يمكننا ملاحظة \n مراحل مختلفة من التطور',
  'يمكن للاعبين دخول حالة \n تدفق وانسجام ',
  'يمكن أن يكون \n زخمًا متصاعدًا أو مفقودًا',
  'إمكانيّة تحول جذري \n أثناء اللعب',
  'التوسع المستمر في توسّع الوقت',
  'توقيت أفعال اللاعبين',
  'التفاعل المباشر المتزامن',
  'تفاعل غير مباشر متتالي',
  'يسمح لجميع المشاركين \n بمراقبة التطوّر',
  'إيقاع أبطأ من التزامن',
  'إذا كان بطيئًا جدًا فإنه يقتل الزخم',
  'يفتح مساحة للتفكير الاستراتيجي \n والعقلاني',
  'يخلق جوًا نشطًا',
  'جو ورشة العمل',
  'يشغّل الإندفاع الجماعي',
  'التفاعلات العفوية',
  'اللإنطلاق مع التيار',
  'تبادل المهارات من خلال \n الملاحظة',
  'يسهّل التكرار',
  'يحفز الحواس',
  ' يمكن أن يخلق توتّر للبعض',
  'يهز المشاركين خارج \n منطقة الراحة',
  'بالنسبة للبعض هو تحويلي',
  'بالنسبة للبعض يكون محبط',
  'من اللعبة',
  'من ديناميات المجموعة',
  'ربط الملاحظات بالنظريات',
  'فتح مساحة آمنة \n لتباين الآراء',
  'البحث عن طرق مختلفة لفهم \n الأفكار',
  'الحدود  الذاتيّة  محترمة',
  'إنها مساحة خالية من الأحكام \n للتعرف على بعضنا البعض',
  'مع اللاعبين',
  'للقطعة / التجربة',
  'انسجام جماعي',
  'الاستماع والنظر إلى \n بعضنا البعض',
  'اتخاذ قرارات جماعية',
  'انسجام فردي',
  'واثق',
  'مستعد',
  'مرح',
  'عفوي وحدسي',
  'انسجام مع موضوع وعالم \n اللعبة',
  'جمع الطاقة',
  'جمع عقولنا',
  'البدء معًا يحدد \n ايقاع الجلسة',
  'منسجم حسيًا',
  'طاقة منفعلة لدخول \n التدفق الإبداعي',
  'متصل بالنفس',
  'كيف تثير الخيال؟',
  'كيف يمكننا تطوير \n هذه العملية؟',
  'كيف تساهم في \n فهمنا؟',
  'بخصوص حدود التجربة',
  'بخصوص التحماية',
  'بخصوص التجارب الفردية',
  'بخصوص المواقف الخاصة',
  'من المحتمل أن يكون مصدر إلهام رئيسي \n للجلسة التالية',
  'بخصوص العمل الجماعي',
  'التغييرات التي طرأت على نظراتهم',
  'استخراج الأفكار \n للجلسة التالية',
  'من طلبات المشاركين',
  'بخصوص الموضوع, التقنيّة  \n و المواد',
  'حول إعادة تفسير \n لعبة معروفة',
  'يمكن للميسر إعادة تفسير \n الطلبات',
  'من التفاصيل الصغيرة \n أثناء المناقشات',
  'من استنتاجات الانعكاس',
  'يقترح لعبة تم تطويرها \n قبل الجلسة',
  'يجرب اللاعبون ويفكّرون \n في تجربتهم',
  'جميع القوانين قابلة للتغيير',
  'يمتلكوا المبادرة و \n تحديد الحدود',
  'يتخذون قرارات جماعيّة',
  'إنشاء اللعبة \n  هو العملية الإبداعية ',
  'التيسير مطلوب',
  'الحفاظ على الوقت',
  ' إبقائها شاملة للكل',
  'تشجيع التكرار والتجربة',
  'تحديد الهدف على اللعب وليس لعب الأدوار',
  'تحديد منطق اللعبة',
  'تؤثر على طريقة اللعب ولكن \n ليس على المنطق',
  'عنصر اللعبة موجود هنا',
  'إذا كانت فعالة في \n تحفيز اللاعبين',
  ' التجارب تبدّل في \n القوانين المتغيّرة',
  'لاستكشاف طرق مختلفة \n من التفاعل',
  'للوصول إلى مزيد من التعقيد \n في النتيجة / التجربة',
  'الموضوع موجود ولكن \n طريقة اللعب غير جذابة',
  'تهدف التجارب إلى العثور على اللعبة \n ضمن هذه الحدود',
  'إذا كانت غير محدودة',
  'إذا كانت مخصصة بشكل واضح \n لمراحل التفكير والتخطيط',
  'يعطي إمكانية تطوير \n رؤية مشتركة',
  'خطر في جو من \n الحكم والنقد',
  'قد لا يتحدث اللاعبون الخجولون',
  'قد تصبح العملية الإبداعية \n عقلانية للغاية',
  'يفضل تواصل حدسي \n أثناء اللعب',
  'يسهل القبول والتدفق',
  'يمكن للقوانين مواجهة \n النكسات المحتملة للتواصل اللفظي',
  'تحديات الكلام \n توفّر امكانيّات لعب كثيرة',
  'بدون أحكام جمالي',
  'اقتراح أفكار عندما يكون ذلك ممكنًا',
  'المساعدة في استخدام الأدوات',
  'ضع اللاعبين المتكاملين معًا',
  'المساعدة في تجاوز العوائق الخاصة بهم',
  'ادفع لاستكشاف إمكاناتهم',
  'التفاعلات التي أنشأتها \n اللعبة',
  'الديناميات الناشئة',
  'هل تندمج الأفعال \n مما يؤدي إلى تعقيد؟',
  'تصرفات كل مشارك',
  'إذا كانوا يفعلون شيئًا آخر \n فما هو؟',
  'تحديد اللحظات الرئيسية',
  'متى ظهر المعنى؟',
  'متى انسجمت المجموعة؟ ',
  'ما الأحداث التي أثرت على \n التطوّرات  بأكملها؟',
  'فكرة انتقلت \n إلى جميع اللاعبين',
  'التفاعلات المؤثّرة على الديناميكية',
  'فضولي وتجريبي',
  'الحالة الأكثر إبداعًا ',
  'جامع للاختلافات',
  'للتعرف على \n الرمزية',
  'للحصول على لمحة \n  من التحدي',
  'تلقائيّة غير مترددة',
  'تكوين إرتباطات حرة',
  'تجاوز العقلاني',
  'تسمح لنا المشاركة بالشعور \n بأن أفكارنا مهمّة',
  'تتيح لنا المشاركة التعرف على \n أوجه التشابه مع الآخرين',
  'كيف عملوا معًا \n عبر تحدياتهم؟',
  'ما هو شعور كل فرد تجاه \n العمل الجماعي',
  'في حالة حدوث توتّر ما',
  'اسمح لهذا بالحدوث وتحدث عنها \n في انعكاس',
  'التعامل معها مباشرة',
  'كيف نؤمّن تواصل سلس ؟',
  'مراعاة قدرتهم \n  على التنظيم الذاتي',
  'هل شعر اللاعبون \n بأنهم أعدّوا  جيّداً؟',
  'هل كان طولها مناسبًا؟',
  'كمخطط عام',
  'ما الذي نجح أو لم ينجح \n كما هو متوقع؟',
  'ما الذي يجعلها جيدة؟',
  'ما الذي يجعلها تفشل؟',
  'بخصوص القوانين',
  'هل كانت واضحة و فيها تحدّي؟',
  'هل فعّلت تفاعل \n وزخم؟',
  ' هل كان من الممكن \n محاولة طرق بديلة؟',
  'بخصوص الأفعال',
  'ما هو  المزاج المناسب؟',
  'هل كانت مثيرة للاهتمام وذات مغزى؟',
  'هل قدموا ما يكفي من \n الإختيارات والتنوع؟',
  'كيف تفاعلوا المشاركون بالمادة؟',
  'هل كان التلاعب به فطري؟',
  'هل كانت ألأدوات مناسبة؟',
  'هل أثارت شيئًا معينًا؟',
  'هل كان الهدف واضحا؟',
  'هل كانت الصيغة مناسبة؟',
  'هل خلق اندفاع؟',
  'هل يساعد رؤاهم في \n إيجاد أرضية مشتركة؟',
  'المفاهيم التي لعبنا بها',
  'الإيحاءات الملموسة',
  'الإيحاءات غير الملموسة',
  'مع إيحائات مادية واضحة ',
  'أول مجموعة ذات إيحائات مادية واضحة ',
  'ثاني مجموعة ذات إيحائات مادية واضحة',
  ' ذات إيحائات واسعة الملامح',
  'أول مجموعة ذات إيحائات \n واسعة الملامح',
  'ثاني مجموعة ذات إيحائات \n واسعة الملامح',
  'ثالث مجموعة ذات إيحائات \n واسعة الملامح',
  'محاكاة الأنظمة الحية',
  'تفاعل عناصر الرسومية الشخصية',
  'استخدام الظل لتحويل الأشكال',
  'إعادة تكييف ألعاب الطاولة وألعاب الفيديو',
  'حصر الأثر بمحيط شكل الأشياء',
  'إنشاء صور من \n نشأت قصص جماعية',
  'توازن أفعالنا',
  'تحليل النماذج الأصلية للألعاب المعروفة',
  ' المواد كوسيلة للتوصيل ما بينا ',
  'بناء آلاتنا الموسيقية الجماعية',
  'الصوت يربط بشكل حميم',
  'تبدأ اللعبة بالإعداد',
  'ألعاب تحديات الحياة الواقعية',
  'القوانين التي تنشئ \n أنماط الحركات',
  'الإرادة الحرة في الحتمية',
  'الرقص على صورة ناشئة',
  'من يقمع من؟',
  'سياقات المختبر تحفز الخيال',
  'تشابك اللاوعي الجماعي ',
  'الترابط من خلال الأحلام',
  'مساحة اللعب كمساحة تعايش',
  'التعلم من خلال التفكير النقدي',
  'ما هي الأفكار التي توصلنا إليها \n من خلال تحرير الفيديو؟',
  'مفاهيم استنتجت من الانعكاسات \n ومقاطع الفيديو',
  'أول مجموعة مفاهيم',
  'ثاني مجموعة مفاهيم',
  'ثالث مجموعة مفاهيم',
  'الصوت والمادة توصل بشكل مشابه \n في حالات التزامن',
  ' البناء كأعمال إبداعية جماعية أساسية',
  'أنماط الفوضى تظهر في التفاصيل',
  'الوعي يخلق معنى',
  'معرفة الذات جسر تجاه الآخرين',
  'كل موقف له لعبة ',
  'قوانين أفضل تجعل \n اللعب أفضل',
  'التجربة أوسع ,ثم الهدف',
  'تظهر الثقافة في تزامن \n الأفعال الإبداعية',
  'الغش هو لعب ،حتى \n الغش يفسد اللعبة',
  'اعتبار المعرفة الجماعية كانضمام \n للمعارف الفردية',
  'لا يستطيع فرد واحد فهم الجميع',
  'الإنعكاس هو قلب التجربة',
  ' المشاركة في إنشاء أنظمتنا \nينتج عن  علاقات عميقة',
  'المزامنة من خلال التشابك المادي',
  'ملاحظات حول الغش',
  'يكشف عن أماكن حيث\n يمكن إضافة قوانين ',
  'لا بجوز أن يتحدى منطق اللعبة',
]
